#!/usr/bin/env python3
"""Train a Keras model with mini-batch gradient descent."""
import tensorflow.keras as K


def train_model(network, data, labels, batch_size, epochs,
                verbose=True, shuffle=False):
    """Train the model with ``network.fit``.

    Args:
        network: the model to train.
        data: numpy.ndarray of shape (m, nx) with the input data.
        labels: one-hot numpy.ndarray of shape (m, classes).
        batch_size: size of the mini-batch.
        epochs: number of passes over the data.
        verbose: whether to print progress during training.
        shuffle: whether to shuffle the batches every epoch.

    Returns:
        The History object generated by ``network.fit``.
    """
    return network.fit(data, labels, batch_size=batch_size, epochs=epochs,
                       verbose=verbose, shuffle=shuffle)
