#!/usr/bin/env python3
"""Train a Keras model with optional validation data."""
import tensorflow.keras as K


def train_model(network, data, labels, batch_size, epochs,
                validation_data=None, verbose=True, shuffle=False):
    """Train the model, optionally validating each epoch.

    Args:
        network: the model to train.
        data: numpy.ndarray of shape (m, nx) with the input data.
        labels: one-hot numpy.ndarray of shape (m, classes).
        batch_size: size of the mini-batch.
        epochs: number of passes over the data.
        validation_data: data to validate the model with, or None.
        verbose: whether to print progress during training.
        shuffle: whether to shuffle the batches every epoch.

    Returns:
        The History object generated by ``network.fit``.
    """
    return network.fit(data, labels, batch_size=batch_size, epochs=epochs,
                       validation_data=validation_data, verbose=verbose,
                       shuffle=shuffle)
