#!/usr/bin/env python3
"""Train a Keras model with optional early stopping."""
import tensorflow.keras as K


def train_model(network, data, labels, batch_size, epochs,
                validation_data=None, early_stopping=False, patience=0,
                verbose=True, shuffle=False):
    """Train the model, optionally stopping early on ``val_loss``.

    Args:
        network: the model to train.
        data: numpy.ndarray of shape (m, nx) with the input data.
        labels: one-hot numpy.ndarray of shape (m, classes).
        batch_size: size of the mini-batch.
        epochs: number of passes over the data.
        validation_data: data to validate the model with, or None.
        early_stopping: whether to use early stopping (needs validation).
        patience: patience used for early stopping.
        verbose: whether to print progress during training.
        shuffle: whether to shuffle the batches every epoch.

    Returns:
        The History object generated by ``network.fit``.
    """
    callbacks = []
    if validation_data and early_stopping:
        callbacks.append(K.callbacks.EarlyStopping(monitor="val_loss",
                                                   patience=patience))
    return network.fit(data, labels, batch_size=batch_size, epochs=epochs,
                       validation_data=validation_data, callbacks=callbacks,
                       verbose=verbose, shuffle=shuffle)
