#!/usr/bin/env python3
"""Train a Keras model with optional best-model checkpointing."""
import tensorflow.keras as K


def train_model(network, data, labels, batch_size, epochs,
                validation_data=None, early_stopping=False, patience=0,
                learning_rate_decay=False, alpha=0.1, decay_rate=1,
                save_best=False, filepath=None, verbose=True,
                shuffle=False):
    """Train the model with early stopping, LR decay and checkpointing.

    Args:
        network: the model to train.
        data: numpy.ndarray of shape (m, nx) with the input data.
        labels: one-hot numpy.ndarray of shape (m, classes).
        batch_size: size of the mini-batch.
        epochs: number of passes over the data.
        validation_data: data to validate the model with, or None.
        early_stopping: whether to use early stopping (needs validation).
        patience: patience used for early stopping.
        learning_rate_decay: whether to decay the learning rate.
        alpha: the initial learning rate.
        decay_rate: the decay rate for the learning rate.
        save_best: whether to save the model with the lowest val_loss.
        filepath: where the best model should be saved.
        verbose: whether to print progress during training.
        shuffle: whether to shuffle the batches every epoch.

    Returns:
        The History object generated by ``network.fit``.
    """
    callbacks = []
    if validation_data:
        if early_stopping:
            callbacks.append(K.callbacks.EarlyStopping(monitor="val_loss",
                                                       patience=patience))
        if learning_rate_decay:
            callbacks.append(K.callbacks.LearningRateScheduler(
                lambda epoch: alpha / (1 + decay_rate * epoch), verbose=1))
        if save_best:
            callbacks.append(K.callbacks.ModelCheckpoint(
                filepath, monitor="val_loss", save_best_only=True))
    return network.fit(data, labels, batch_size=batch_size, epochs=epochs,
                       validation_data=validation_data, callbacks=callbacks,
                       verbose=verbose, shuffle=shuffle)
